server:
  port: 8090

grpc:
  client:
    MemberProfile:
      address: static://localhost:8011
      negotiation-type: plaintext

spring:
  config:
    import:
      - app/cors/cors.yml
      - app/time/time.yml # classpath:/app/time/time.yml
      - app/jasypt/jasypt.yml

  application:
    name: board-application

  # Default active profile name
  profiles:
    active: prod

  mvc:
    converters:
      preferred-json-mapper: gson

  data:
    mongodb:
      database: board
      uri: mongodb://localhost:27037/board?authSource=admin
      host: localhost
      port: 27037
      username: root
      password: root
      authentication-database: admin

#  datasource:
#    driver-class-name:
#    # 운영계: 환경변수
#    url: ${db.url:jdbc:postgresql://localhost:5432/bff?currentSchema=board} # ${환경변수}, ${환경변수:기본값}
#    username: ${db.username:root}
#    password: ${db.password:root}
#    hikari:
#      connectionTimeout: 100_000
#      idleTimeout: 600000
#      maximum-pool-size: 300
#      minimum-idle: 5
#      maxLifetime: 10000
#      leak-detection-threshold: 2000
#
#  jpa:
#    properties:
#      hibernate:
#        format-sql: false
#        dialect: org.hibernate.dialect.PostgreSQL10Dialect
#    show-sql: true
#    hibernate:
#      ddl-auto: none # `validation` or `none`
#
#
#
#  flyway:
#    enabled: true
#    baseline-on-migrate: true
#    locations: classpath:/db/migration # 기본값

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
