server:
  port: 8080

grpc:
  client:
    MemberProfile:
      address: static://localhost:8011
      negotiation-type: plaintext

spring:
  config:
    import:
      - app/cors/cors.yml
      - app/time/time.yml # classpath:/app/time/time.yml
      - app/jasypt/jasypt.yml

  application:
    name: member-application

  # Default active profile name
  profiles:
    active: prod

  mvc:
    converters:
      preferred-json-mapper: gson

  datasource:
    driver-class-name:
    # 운영계: 환경변수
    url: ${db.url:jdbc:postgresql://localhost:5432/bff?currentSchema=member} # ${환경변수}, ${환경변수:기본값}
    username: ${db.username:root}
    password: ${db.password:root}
    hikari:
      connectionTimeout: 100_000
      idleTimeout: 600000
      maximum-pool-size: 300
      minimum-idle: 5
      maxLifetime: 10000
      leak-detection-threshold: 2000

  jpa:
    properties:
      hibernate:
        format-sql: false
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: true
    hibernate:
      ddl-auto: none # `validation` or `none`



  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:/db/migration # 기본값

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
